### ISSUE TITLE
Import account  -  Please force lowercase on account input

### ISSUE THREAD

**Issue by telos-justin** [telosnetwork/telos-keycat#12]
To prevent any issues

**Comment by smilingkylan** [comment]
I have forced the account to be lowercase when going from the "Create Account" page to the "Review" page. The "Review" page will enforce lowercase, and even includes hints to make sure the account name is all in lowercase.

Due to the way browsers handle forms, we are unable to intercept form input until the form is submitted. I believe this is a security policy, and therefore we cannot actually prevent a user from entering an account handle that has uppercase letters. We can inform them of the issue by adding hints to labels and in error messages.
